(TeX-add-style-hook "master"
 (lambda ()
    (TeX-run-style-hooks
     "tikz"
     "fontenc"
     "T2A"
     "babel"
     "english"
     "bulgarian"
     "inputenc"
     "utf8"
     "graphicx"
     "listings"
     "latex2e"
     "rep10"
     "report"
     "title"
     "intro"
     "overview"
     "modules"
     "implementation"
     "manual"
     "conclusion"
     "appendix")))

